# Generated by Django 5.2 on 2026-08-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
            ],
        ),
    ]
